import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="599438915382-sfacj2hbnv6sio7qkdt9bhm38668j02d.apps.googleusercontent.com">
        <body className={inter.className}>
          <Providers>{children}</Providers>
          <Toaster />
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
